parameters:
#    mystah_craft_user.example.class: MystahCraft\UserBundle\Example

services:
#    mystah_craft_user.example:
#        class: %mystah_craft_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
