mystah_craft_site_homepage:
    pattern:  /{page}
    defaults: { _controller: "MystahCraftSiteBundle:Default:index", page:1 }
    requirements:
        page: \d+

mystah_craft_site_joueurs:
    pattern:  /joueurs
    defaults: { _controller: "MystahCraftSiteBundle:Default:joueurs" }
    
mystah_craft_site_histoire:
    pattern:  /histoire
    defaults: { _controller: "MystahCraftSiteBundle:Default:histoire" }

mystah_craft_site_screen:
    pattern:  /screenshots
    defaults: { _controller: "MystahCraftSiteBundle:Default:screen" }
    
mystah_craft_site_liens:
    pattern:  /liens
    defaults: { _controller: "MystahCraftSiteBundle:Default:liens" }
    
mystah_craft_site_article:
    pattern: /article/{slug}
    defaults: { _controller: "MystahCraftSiteBundle:Default:article" }