parameters:
#    mystah_craft_site.example.class: MystahCraft\SiteBundle\Example

services:
#    mystah_craft_site.example:
#        class: %mystah_craft_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
