admin_homepage:
    pattern: /
    defaults: { _controller: "MystahCraftAdminBundle:Voir:index" }
    
admin_contenus:
    pattern: /contenus/{type}
    defaults: { _controller: "MystahCraftAdminBundle:Voir:contenus" }
    requirements:
        type: .+
    
admin_contenu:
    pattern: /contenu/{type}/{id}
    defaults: { _controller: "MystahCraftAdminBundle:Voir:contenu" }
    requirements:
        type: .+
        id: \d+

admin_ajouter_contenu:
    pattern:  /contenus/{type}/ajouter
    defaults: { _controller: "MystahCraftAdminBundle:Ajouter:contenus" }

    
admin_modifier_contenu:
    pattern:  /contenus/{type}/modifier/{id}
    defaults: { _controller: "MystahCraftAdminBundle:Modifier:contenus" }
    requirements:
        type: .+
        id: \d+
        
admin_supprimer_contenu:
    pattern:  /contenus/{type}/supprimer/{id}
    defaults: { _controller: "MystahCraftAdminBundle:Modifier:contenus" }
    requirements:
        type: .+
        id: \d+