admin_homepage:
    pattern: /
    defaults: { _controller: "MystahCraftAdminBundle:Voir:index" }
    
admin_contenus:
    pattern: /contenus/type/{type}
    defaults: { _controller: "MystahCraftAdminBundle:Voir:contenus" }
    
admin_contenu:
    pattern: /contenu/{id}
    defaults: { _controller: "MystahCraftAdminBundle:Voir:contenu" }
    requirements:
        id: \d+

admin_ajouter_contenu:
    pattern:  /contenus/type/{type}/ajouter
    defaults: { _controller: "MystahCraftAdminBundle:Ajouter:contenus" }

    
admin_modifier_contenu:
    pattern:  /contenus/modifier/{id}
    defaults: { _controller: "MystahCraftAdminBundle:Modifier:contenus" }
    requirements:
        id: \d+
        
admin_supprimer_contenu:
    pattern:  /contenus/supprimer/{id}
    defaults: { _controller: "MystahCraftAdminBundle:Supprimer:contenus" }
    requirements:
        id: \d+