parameters:
#    mystah_craft_admin.example.class: MystahCraft\AdminBundle\Example

services:
#    mystah_craft_admin.example:
#        class: %mystah_craft_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    mystah_craft_admin.contenus:
        class: MystahCraft\AdminBundle\Contenus\GestionOngletsContenus
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: twig.extension }
