parameters:
#    mystah_craft_admin.example.class: MystahCraft\AdminBundle\Example

services:
#    mystah_craft_admin.example:
#        class: %mystah_craft_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
